### ISSUE TITLE
Ne marche plus suite au changement de nom de domaine 

### ISSUE THREAD

**Issue by nsagot** [Plenituz/univ-schedule#1]
Hello,

L'app ne marche plus car l'université de Valenciennes est devenu L'UPHF le système d'authentification est le même mais le nom de domaine a changé

**Comment by GuyGuy59** [comment]
Hello , 

je suis entrain de regarder au code pour  le mettre à jour , le dev n'est plus à l'univ de va

**Comment by nsagot** [comment]
Parfait merci !

**Comment by ghost** [comment]
J'ai créé une Pull Request pour mettre à jour les URLs suite au changement du nom de domaine de l'Université https://github.com/Plenituz/univ-schedule/pull/2

**Comment by GuyGuy59** [comment]
Merci , cote lien tous est ok . Maintenant faut build tous ça

**Comment by Plenituz** [comment]
Merci les gars de garder un oeil la decu, j'ai build et mis en ligne la nouvelle version, vous pourrez me confirmer par mail que la nouvelle version fonctionne une fois que vous avez recu l'update ?

**Comment by GuyGuy59** [comment]
Je confirme l apk , fonctionne
